[env:esp32-s3-n16r8-usbserial]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
lib_deps =
  fastled/FastLED
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DLW_MAX_PIXELS=300
