/**
 * export.js — serialise pixel maps to WLED / FastLED / CSV formats
 *
 * WLED ledmap.json schema:
 *   { "n": <totalLEDs>, "map": [[x,y], [x,y], ...] }
 *   Upload via WLED web UI → Config → LED Preferences → 2D setup → Custom ledmap
 *
 * Coordinates are in draw order (strip 0 pixel 0, strip 0 pixel 1, ... strip 1 pixel 0, ...)
 */

/**
 * @typedef {{ x: number, y: number, index: number }} Pixel
 * @typedef {{ normalize?: boolean, scaleX?: number, scaleY?: number, offsetX?: number, offsetY?: number }} ExportOpts
 */

/**
 * @param {Pixel[]} pixels
 * @param {ExportOpts} opts
 * @returns {string}  pretty-printed JSON
 */
export function toWLEDLedmap(pixels, opts = {}) {
  const {
    normalize = true,
    scaleX  = 1, scaleY  = 1,
    offsetX = 0, offsetY = 0,
  } = opts;

  // Sort by index to guarantee order
  const sorted = [...pixels].sort((a, b) => a.index - b.index);
  let coords = sorted.map(px => [px.x, px.y]);

  if (normalize && coords.length > 0) {
    const xs = coords.map(c => c[0]);
    const ys = coords.map(c => c[1]);
    const minX = Math.min(...xs), maxX = Math.max(...xs);
    const minY = Math.min(...ys), maxY = Math.max(...ys);
    const rangeX = maxX - minX || 1; // avoid /0 for collinear vertical/horizontal strips
    const rangeY = maxY - minY || 1;
    coords = coords.map(([x, y]) => [
      (x - minX) / rangeX,
      (y - minY) / rangeY,
    ]);
  }

  const map = coords.map(([x, y]) => [
    r2(x * scaleX + offsetX),
    r2(y * scaleY + offsetY),
  ]);

  return JSON.stringify({ n: pixels.length, map }, null, 2);
}

/**
 * @param {Pixel[]} pixels
 * @param {ExportOpts} opts
 * @returns {string}  C++ header snippet
 */
export function toFastLED(pixels, opts = {}) {
  const data  = JSON.parse(toWLEDLedmap(pixels, opts));
  const lines = data.map.map((pt, i) => `  {${pt[0]}f, ${pt[1]}f},  // LED ${i}`);
  return [
    `// FastLED 2D coordinate map — ${pixels.length} LEDs`,
    `// Generated by Light Weaver`,
    ``,
    `struct Point { float x, y; };`,
    `const Point ledCoords[${pixels.length}] PROGMEM = {`,
    ...lines,
    `};`,
  ].join('\n');
}

/**
 * @param {Pixel[]} pixels
 * @returns {string}  CSV with header row
 */
export function toCSV(pixels) {
  const sorted = [...pixels].sort((a, b) => a.index - b.index);
  const rows   = sorted.map(px => `${px.index},${px.x.toFixed(3)},${px.y.toFixed(3)}`);
  return `index,x,y\n${rows.join('\n')}`;
}

/**
 * Trigger a browser file download.
 * @param {string} content
 * @param {string} filename
 * @param {string} mimeType
 */
export function download(content, filename, mimeType = 'application/json') {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  a.click();
  URL.revokeObjectURL(url);
}

/** Round to 2 decimal places */
function r2(n) { return Math.round(n * 100) / 100; }

if (import.meta.hot) import.meta.hot.accept();
