export const CORE_CARD_PATTERN_BANK = Object.freeze([
  {
    id: 'aurora',
    label: 'Aurora',
    description: 'Slow green and violet curtains.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#003311,#00cc66,#00ffaa,#6600aa,#003311)',
  },
  {
    id: 'plasma',
    label: 'Plasma',
    description: 'Liquid color fields that fold through each other.',
    mode: 'procedural',
    preview: 'linear-gradient(135deg,#7400b8,#5390d9,#06d6a0,#9bf6ff,#7400b8)',
  },
  {
    id: 'fire',
    label: 'Fire',
    description: 'Warm flame motion for bright centerpiece pieces.',
    mode: 'procedural',
    preview: 'linear-gradient(0deg,#330000,#cc2200,#ff6600,#ffcc00,#ffffff)',
  },
  {
    id: 'ocean',
    label: 'Ocean',
    description: 'Blue and teal rolling wave movement.',
    mode: 'procedural',
    preview: 'linear-gradient(180deg,#ffffff 0%,#7aecff 20%,#0077b6 60%,#03045e 100%)',
  },
  {
    id: 'ripple',
    label: 'Ripple',
    description: 'Rings expanding through the artwork.',
    mode: 'procedural',
    preview: 'radial-gradient(circle,#ffffff 0%,#00ccff 20%,#0033aa 50%,#000022 80%)',
  },
  {
    id: 'lava',
    label: 'Lava Lamp',
    description: 'Slow orange and red organic blobs.',
    mode: 'procedural',
    previewPatternId: 'lava',
    preview: 'radial-gradient(ellipse at 30% 70%,#ff4400 0%,#cc0000 30%,#220000 100%)',
  },
  {
    id: 'rainbow',
    label: 'Rainbow',
    description: 'Full-spectrum color flow across the strip.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#ff0000,#ffff00,#00ff00,#00ffff,#0000ff,#ff00ff,#ff0000)',
  },
  {
    id: 'sparkle',
    label: 'Sparkle',
    description: 'Random bright points over a deep base.',
    mode: 'procedural',
    preview: 'radial-gradient(circle at 20% 50%,#fff 0%,transparent 8%),radial-gradient(circle at 60% 30%,#fff 0%,transparent 6%),radial-gradient(circle at 80% 70%,#fff 0%,transparent 10%),#080820',
  },
  {
    id: 'twinkle',
    label: 'Twinkle',
    description: 'Soft star-like pulsing points.',
    mode: 'procedural',
    preview: 'radial-gradient(circle at 15% 80%,#aaddff 0%,transparent 5%),radial-gradient(circle at 55% 20%,#ffeedd 0%,transparent 4%),radial-gradient(circle at 85% 60%,#ccffee 0%,transparent 6%),#040412',
  },
  {
    id: 'meteor',
    label: 'Meteor',
    description: 'Comets with glowing tails.',
    mode: 'procedural',
    previewPatternId: 'meteor',
    preview: 'linear-gradient(90deg,#000010,#000030 40%,#8888ff 80%,#ffffff 100%)',
  },
  {
    id: 'chase',
    label: 'Color Chase',
    description: 'A bright dot racing around the piece.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#050510 0%,#050510 35%,#4cc9f0 50%,#ffffff 51%,#4cc9f0 65%,#050510 100%)',
  },
  {
    id: 'scanner',
    label: 'Scanner',
    description: 'A single beam sweeps back and forth.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#050505 0%,#ff2000 40%,#ffffff 50%,#ff2000 60%,#050505 100%)',
  },
  {
    id: 'breathe',
    label: 'Breathe',
    description: 'Slow ambient pulsing glow.',
    mode: 'procedural',
    preview: 'radial-gradient(ellipse,#06d6a0 0%,#036644 50%,#010e09 100%)',
  },
  {
    id: 'candle',
    label: 'Candle',
    description: 'Small warm flicker for calm pieces.',
    mode: 'procedural',
    preview: 'radial-gradient(ellipse at 50% 80%,#ffffff 0%,#ffee88 10%,#ff7700 40%,#220000 100%)',
  },
  {
    id: 'ember',
    label: 'Ember',
    description: 'Deeper warm glow with uneven motion.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#2a0800,#8a2008,#d04a18,#8a2008,#2a0800)',
  },
  {
    id: 'lightning',
    label: 'Lightning',
    description: 'Random electric strikes.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#050515,#7070ff,#ffffff,#7070ff,#050515)',
  },
  {
    id: 'neon',
    label: 'Neon',
    description: 'Flickering colored tube segments.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#ff00aa,#ff00aa 33%,#00ffcc 33%,#00ffcc 66%,#ffff00 66%)',
  },
  {
    id: 'matrix',
    label: 'Digital Rain',
    description: 'Green cascading digital rain.',
    mode: 'procedural',
    previewPatternId: 'matrix',
    preview: 'linear-gradient(180deg,#ffffff 0%,#00ff41 15%,#003b00 60%,#000000 100%)',
  },
  {
    id: 'heartbeat',
    label: 'Heartbeat',
    description: 'A double pulse with a quiet resting glow.',
    mode: 'procedural',
    preview: 'radial-gradient(ellipse,#ff0022 0%,#880011 50%,#110003 100%)',
  },
  {
    id: 'stained',
    label: 'Stained Glass',
    description: 'Color panes with dark vein separation.',
    mode: 'procedural',
    preview: 'conic-gradient(from 0deg at 50% 50%,#ff2200,#ffaa00,#00dd44,#0066ff,#cc00ff,#ff2200)',
  },
  {
    id: 'confetti',
    label: 'Confetti',
    description: 'Random colored sparks.',
    mode: 'procedural',
    preview: 'radial-gradient(circle at 20% 30%,#ff0066 0%,transparent 8%),radial-gradient(circle at 70% 60%,#00ff88 0%,transparent 6%),radial-gradient(circle at 50% 80%,#ffcc00 0%,transparent 7%),#080808',
  },
  {
    id: 'warp',
    label: 'Warp Speed',
    description: 'White and blue streaks flying outward.',
    mode: 'procedural',
    preview: 'radial-gradient(circle,#ffffff 0%,#8888ff 10%,#000022 50%,#000000 100%)',
  },
  {
    id: 'pulse-ring',
    label: 'Pulse Ring',
    description: 'A bright pulse travels from the center outward.',
    mode: 'procedural',
    preview: 'radial-gradient(circle,#ffffff 0%,#ff00ff 18%,#110022 62%,#000000 100%)',
  },
  {
    id: 'blocks',
    label: 'Color Blocks',
    description: 'Bold blocks of color moving in steps.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#ff0066 0 20%,#ffcc00 20% 40%,#00cc66 40% 60%,#0099ff 60% 80%,#6633ff 80%)',
  },
  {
    id: 'bloom',
    label: 'Bloom',
    description: 'Soft floral pink and gold pulses.',
    mode: 'procedural',
    preview: 'radial-gradient(circle,#ffd6f0 0%,#ff5ab3 24%,#46102e 62%,#09030b 100%)',
  },
  {
    id: 'calm',
    label: 'Calm',
    description: 'Low, slow blue-green breathing.',
    mode: 'procedural',
    preview: 'linear-gradient(120deg,#071923,#14515c,#1f8076,#071923)',
  },
  {
    id: 'drift',
    label: 'Drift',
    description: 'A slow pastel hue drift.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#7fc7ff,#d9a8ff,#ffc2d6,#ffe7a8,#7fc7ff)',
  },
  {
    id: 'wave',
    label: 'Wave',
    description: 'Structured blue-purple sine waves.',
    mode: 'procedural',
    preview: 'linear-gradient(90deg,#1a1a4a,#5c5cc8,#9b9be0,#5c5cc8,#1a1a4a)',
  },
  {
    id: 'sunset',
    label: 'Sunset',
    description: 'Warm magenta, orange, and gold drift.',
    mode: 'procedural',
    previewPatternId: 'sunrise',
    preview: 'linear-gradient(90deg,#2a0830,#8a2050,#d04a18,#f1c40f,#d04a18,#8a2050,#2a0830)',
  },
  {
    id: 'warm-white',
    label: 'Warm White',
    description: 'A steady warm installation white.',
    mode: 'preset',
    preview: 'linear-gradient(90deg,#3a2c1a,#c89b5c,#f4ede0,#c89b5c,#3a2c1a)',
  },
]);

const EXTENDED_CARD_PATTERN_BANK = Object.freeze([
  { id: 'gradient', label: 'Gradient', description: 'Static colour gradient from palette start to end', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'linear-gradient(90deg,#ef476f,#ffd166,#06d6a0,#118ab2)' },
  { id: 'debug-xy', label: 'XY Position Map', description: 'Developer tool: x maps to hue, y to brightness', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'linear-gradient(135deg,#ff0000,#00ff00,#0000ff)' },
  { id: 'glitch', label: 'Glitch', description: 'Digital corruption - random color jumps and block freezes', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(90deg,#00ffff 0% 15%,#ff00ff 15% 30%,#000000 30% 45%,#ffff00 45% 60%,#ff0000 60% 75%,#00ffff 75% 100%)' },
  { id: 'inkdrop', label: 'Ink Drop', description: 'Dark ink slowly diffusing and cycling through deep colors', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'radial-gradient(ellipse,#330066 0%,#000066 30%,#001133 60%,#000000 100%)' },
  { id: 'strobe', label: 'Strobe Beat', description: 'Sharp flash on every beat - tunable hue and duty cycle', mode: 'procedural', preset: 'neon', previewPatternId: 'neon', preview: 'linear-gradient(90deg,#050505,#ffffff,#050505)' },
  { id: 'binary-pulse', label: 'Binary Pulse', description: 'Each LED section blinks on a different prime-based rhythm', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(90deg,#000000 0% 45%,#ffffff 45% 55%,#000000 55% 100%)' },
  { id: 'sunrise-v2', label: 'Sunrise Horizon Soft', description: 'Gradual warm dawn gradient rising from base to top', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'linear-gradient(0deg,#330011 0%,#cc2200 30%,#ff6600 60%,#ffcc44 85%,#ffffaa 100%)' },
  { id: 'crystal', label: 'Crystal', description: 'Faceted gem-like reflections with prismatic color', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'conic-gradient(from 30deg,#aaeeff,#ffffff,#aaeeff,#eeffff,#aaeeff)' },
  { id: 'smoke', label: 'Smoke', description: 'Dark turbulent smoke clouds billowing slowly', mode: 'procedural', preset: 'drift', previewPatternId: 'drift', preview: 'radial-gradient(ellipse,#aaaaaa 0%,#555566 40%,#111122 100%)' },
  { id: 'ice', label: 'Ice Crystal', description: 'Cold blue crystalline frost patterns', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'linear-gradient(135deg,#aaddff,#eeffff,#88ccff,#ffffff)' },
  { id: 'volt', label: 'Volt', description: 'Electric crackling arcs with audio-reactive energy', mode: 'procedural', preset: 'lightning', previewPatternId: 'lightning', preview: 'linear-gradient(90deg,#000022,#3333ff,#aaaaff,#ffffff,#3333ff,#000022)' },
  { id: 'waterfall', label: 'Waterfall', description: 'Cascading blue-white streams flowing downward', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'linear-gradient(180deg,#eeffff 0%,#88ddff 30%,#2299cc 70%,#003355 100%)' },
  { id: 'galaxy', label: 'Galaxy', description: 'Spiral arms of stars rotating around a bright core', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'radial-gradient(ellipse,#ffffff 0%,#aaaaff 10%,#221133 50%,#000011 100%)' },
  { id: 'bass-pulse', label: 'Bass Pulse', description: 'Radial rings that explode outward on every bass beat', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'radial-gradient(circle,#ff6600,#aa0033,#000033)' },
  { id: 'spectrum', label: 'Spectrum Bars', description: 'Real-time audio spectrum displayed as vertical bars', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'linear-gradient(90deg,#ff0000,#ffff00,#00ff00,#00ffff,#0000ff)' },
  { id: 'vortex', label: 'Vortex', description: 'Hypnotic rotating spiral arms pulling toward center', mode: 'procedural', preset: 'warp', previewPatternId: 'warp', preview: 'conic-gradient(from 0deg,#ff00ff,#00ffff,#ffff00,#ff00ff)' },
  { id: 'comet', label: 'Comet', description: 'Multiple streaking comets with glowing tails', mode: 'procedural', preset: 'meteor', previewPatternId: 'meteor', preview: 'linear-gradient(135deg,#ffffff,#88aaff,#001133)' },
  { id: 'snowfield', label: 'Snowfield', description: 'Gently drifting snowflakes with varying speeds', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'linear-gradient(180deg,#000033 0%,#112244 50%,#ffffff 100%)' },
  { id: 'mandala', label: 'Mandala', description: 'Symmetrical mandala petals responding to bass', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'radial-gradient(circle,#ffcc44,#ff6600,#220044)' },
  { id: 'color-organ', label: 'Color Organ', description: 'Each audio band controls a separate color zone with smooth blending', mode: 'procedural', preset: 'rainbow', previewPatternId: 'rainbow', preview: 'linear-gradient(135deg,#ff0044,#44ff00,#0044ff)' },
  { id: 'lissajous', label: 'Lissajous', description: 'Animated Lissajous curves drawing geometric shapes', mode: 'procedural', preset: 'ripple', previewPatternId: 'ripple', preview: 'radial-gradient(ellipse,#00ffaa,#0088ff,#000022)' },
  { id: 'solar', label: 'Solar Flare', description: 'Radiant solar corona with erupting plasma tendrils', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'radial-gradient(circle,#ffffff 0%,#ffee00 15%,#ff6600 40%,#220000 100%)' },
  { id: 'prism', label: 'Prism', description: 'White light split through a crystal prism into spectral bands', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'linear-gradient(135deg,#ff0000,#ff8800,#ffff00,#00ff00,#0088ff,#8800ff)' },
  { id: 'dna', label: 'DNA Helix', description: 'Double helix spiraling through the LED array', mode: 'procedural', preset: 'rainbow', previewPatternId: 'rainbow', preview: 'linear-gradient(135deg,#0044ff,#00ff88,#0044ff)' },
  { id: 'fluid', label: 'Fluid', description: 'Incompressible fluid swirl with pressure-based coloring', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'conic-gradient(from 45deg,#0033aa,#00aaff,#00ffdd,#0033aa)' },
  { id: 'circuit', label: 'Circuit', description: 'Electronic circuit board traces with pulsing data packets', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(135deg,#001100,#003300,#00aa44,#001100)' },
  { id: 'nova', label: 'Nova', description: 'Supernova explosion with shockwave rings expanding outward', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'radial-gradient(circle,#ffffff 0%,#ffcc00 20%,#ff2200 50%,#110022 100%)' },
  { id: 'tide', label: 'Tide', description: 'Gentle ocean tide - waves lapping and receding', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'linear-gradient(180deg,#001133 0%,#003366 30%,#0066aa 60%,#88ccff 100%)' },
  { id: 'hyperspace', label: 'Hyperspace', description: 'Warp speed jump - stars stretching into light streaks', mode: 'procedural', preset: 'meteor', previewPatternId: 'meteor', preview: 'radial-gradient(circle at center,#ffffff 0%,#8888ff 15%,#000011 60%,#000000 100%)' },
  { id: 'zen', label: 'Zen', description: 'Slow meditative breathing - minimal geometric mandala', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'radial-gradient(circle,#334455 0%,#111122 50%,#050510 100%)' },
  { id: 'glitter', label: 'Glitter', description: 'Dense holographic glitter with shifting rainbow shimmer', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'radial-gradient(circle at 30% 40%,#ffffff,transparent 20%),radial-gradient(circle at 70% 60%,#ffaaff,transparent 25%),#220033' },
  { id: 'morse', label: 'Morse', description: 'Dots and dashes chasing across the strip in morse code rhythm', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(90deg,#000011,#000011 40%,#4488ff 45%,#ffffff 50%,#4488ff 55%,#000011 60%,#000011)' },
  { id: 'bubble', label: 'Bubbles', description: 'Iridescent soap bubbles rising and popping', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(circle at 25% 60%,#aaffee,transparent 30%),radial-gradient(circle at 65% 35%,#ffaacc,transparent 25%),radial-gradient(circle at 80% 70%,#aaccff,transparent 20%),#000011' },
  { id: 'strobe-bpm', label: 'Strobe BPM', description: 'Hard strobe synced to BPM - use at low brightness', mode: 'procedural', preset: 'neon', previewPatternId: 'neon', preview: 'linear-gradient(90deg,#ffffff,#000000)' },
  { id: 'kick-flash', label: 'Kick Flash', description: 'Ring flash on every beat, bass amplified', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'radial-gradient(circle,#ffffff 0%,#ff2200 40%,#000000 100%)' },
  { id: 'beat-grid', label: 'Beat Grid', description: 'Geometric grid tiles that flash on each beat', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'linear-gradient(45deg,#222244,#4444aa)' },
  { id: 'pulse-expand', label: 'Pulse Expand', description: 'Radial pulse expanding outward on every beat', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'radial-gradient(circle,#ff00ff 0%,#000033 70%)' },
  { id: 'confetti-bpm', label: 'Confetti Beat', description: 'Random color confetti explosion synced to each beat', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'conic-gradient(from 0deg,#ff0000,#00ff00,#0000ff,#ffff00,#ff00ff,#ff0000)' },
  { id: 'ribbons', label: 'Silk Ribbons', description: 'Flowing layered color ribbons twisting through space', mode: 'procedural', preset: 'chase', previewPatternId: 'chase', preview: 'linear-gradient(45deg, #ff4488, #ff8800, #ffff00, #00ff88, #0088ff, #8800ff)' },
  { id: 'tesseract', label: 'Tesseract', description: 'Rotating 4D hypercube projection with geometric precision', mode: 'procedural', preset: 'warp', previewPatternId: 'warp', preview: 'conic-gradient(from 45deg, #001166, #0033ff, #0088ff, #00ffff, #001166)' },
  { id: 'zodiac', label: 'Zodiac Wheel', description: 'Rotating astrology wheel with glowing constellation segments', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'conic-gradient(from 0deg, #220033, #6600cc, #220033, #6600cc, #220033)' },
  { id: 'constellation', label: 'Constellation', description: 'Star field with connected constellation lines pulsing', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'radial-gradient(circle, #ffffff 1%, #001133 20%, #000000 100%)' },
  { id: 'pendulum', label: 'Pendulum', description: 'Swinging pendulum traces Lissajous patterns in light', mode: 'procedural', preset: 'ripple', previewPatternId: 'ripple', preview: 'radial-gradient(ellipse, #ffff44 0%, #ff8800 30%, #440000 100%)' },
  { id: 'iceberg', label: 'Iceberg', description: 'Deep blue underwater gradients with surface light caustics', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'linear-gradient(180deg, #cceeFF 0%, #0044aa 40%, #001133 100%)' },
  { id: 'soundwave', label: 'Sound Wave', description: 'Classic oscilloscope-style sine wave display', mode: 'procedural', preset: 'ripple', previewPatternId: 'ripple', preview: 'linear-gradient(90deg, #000022 0%, #003366 50%, #000022 100%)' },
  { id: 'mandelbrot', label: 'Mandelbrot', description: 'Classic Mandelbrot set fractal rendered in real-time', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'radial-gradient(circle, #ff8800 10%, #220000 40%, #000033 70%, #001166 100%)' },
  { id: 'cityscape', label: 'Cityscape', description: 'Night skyline silhouette with glowing windows', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'linear-gradient(180deg, #000011 0%, #001133 50%, #ff8800 70%, #ffcc00 100%)' },
  { id: 'lotus', label: 'Lotus Bloom', description: 'Unfolding lotus flower petals with soft radial glow', mode: 'procedural', preset: 'breathe', previewPatternId: 'breathe', preview: 'radial-gradient(circle, #ffaacc 0%, #ff4488 40%, #220022 100%)' },
  { id: 'northern', label: 'Northern Lights', description: 'Slow sweeping aurora borealis curtains', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'linear-gradient(180deg,#001020 0%,#004030 40%,#00aa88 70%,#00ffcc 90%,#8844ff 100%)' },
  { id: 'kaleido', label: 'Kaleidoscope', description: 'Mirrored radial symmetry pattern with evolving geometry', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'conic-gradient(from 0deg, #ff0088, #8800ff, #0088ff, #00ff88, #ff0088)' },
  { id: 'watercolor', label: 'Watercolor Wash', description: 'Soft blending washes of color drifting across the canvas', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(ellipse at 30% 40%, #ff9988 0%, #cc44aa 40%, #4466ff 100%)' },
  { id: 'digitrain', label: 'Digital Rain', description: 'Matrix-style falling columns of green characters', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(180deg, #001500, #003300, #00ff41 80%, #ffffff)' },
  { id: 'sunrise', label: 'Sunrise', description: 'Warm horizon glow transitioning from deep purple to golden daylight', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'linear-gradient(180deg, #220033 0%, #8800aa 30%, #ff4400 60%, #ff9900 80%, #ffdd00 100%)' },
  { id: 'fractal', label: 'Fractal Noise', description: 'Layered octave noise creating organic fractal texture', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'radial-gradient(circle, #ffffff 0%, #8888ff 30%, #4400aa 60%, #110022 100%)' },
  { id: 'thermal', label: 'Thermal Vision', description: 'Infrared thermal camera simulation with cold-to-hot color mapping', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'linear-gradient(90deg, #000066 0%, #0066ff 25%, #00ff66 45%, #ffff00 65%, #ff4400 80%, #ffffff 100%)' },
  { id: 'jellyfish', label: 'Jellyfish', description: 'Pulsating translucent jellyfish drifting upward', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(ellipse 60% 80% at 50% 70%, #ffffff44 0%, #8800ff88 40%, #440088 70%, #000022 100%)' },
  { id: 'pixelate', label: 'Pixel Art', description: 'Animated low-resolution pixel blocks with cycling colors', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'linear-gradient(45deg, #ff0000 0%, #00ff00 33%, #0000ff 66%, #ffff00 100%)' },
  { id: 'smoke-haze', label: 'Smoke & Haze', description: 'Billowing smoke tendrils with shifting opacity', mode: 'procedural', preset: 'drift', previewPatternId: 'drift', preview: 'linear-gradient(180deg, #cccccc 0%, #888888 40%, #444444 70%, #111111 100%)' },
  { id: 'lava-lamp', label: 'Lava Lamp', description: 'Slow blobs of color rising and falling', mode: 'procedural', preset: 'lava', previewPatternId: 'lava', preview: 'linear-gradient(180deg, #ff6600 0%, #cc0044 50%, #440022 100%)' },
  { id: 'aurora-borealis', label: 'Aurora Borealis', description: 'Vertical curtains of pale green and violet light', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'linear-gradient(90deg, #003322 0%, #00ffaa 30%, #4400aa 60%, #00ffaa 80%, #003322 100%)' },
  { id: 'circuit-board', label: 'Circuit Board', description: 'Pulsing data packets along PCB traces', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(135deg, #001100 0%, #003300 40%, #00ff44 60%, #001100 100%)' },
  { id: 'wormhole', label: 'Wormhole', description: 'Spiraling tunnel into infinite depth', mode: 'procedural', preset: 'warp', previewPatternId: 'warp', preview: 'radial-gradient(circle, #ffffff 0%, #4400aa 30%, #000044 60%, #000000 100%)' },
  { id: 'bioluminescence', label: 'Bioluminescence', description: 'Glowing sea creatures moving through dark water', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(circle at 30% 60%, #00ffcc44, transparent), radial-gradient(circle at 70% 30%, #0044ff44, transparent), linear-gradient(180deg, #000022, #001133)' },
  { id: 'prismatic', label: 'Prismatic', description: 'White light splitting into spectrum bands', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'linear-gradient(90deg, #ff0000, #ff8800, #ffff00, #00ff00, #0088ff, #8800ff)' },
  { id: 'meteor-shower', label: 'Meteor Shower', description: 'Streaking meteors with glowing tails', mode: 'procedural', preset: 'meteor', previewPatternId: 'meteor', preview: 'linear-gradient(150deg, #000011 0%, #001133 40%, #ffffff88 50%, #000011 60%)' },
  { id: 'pixel-rain', label: 'Pixel Rain', description: 'Columns of falling glowing pixels', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(180deg, #000000 0%, #00ff00 40%, #003300 80%)' },
  { id: 'crystallize', label: 'Crystallize', description: 'Geometric crystal facets refracting light', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'linear-gradient(135deg, #88ccff 0%, #ffffff 30%, #aaddff 50%, #4488cc 80%, #88ccff 100%)' },
  { id: 'hypnotic-spiral', label: 'Hypnotic Spiral', description: 'Mesmerizing rotating concentric rings', mode: 'procedural', preset: 'warp', previewPatternId: 'warp', preview: 'conic-gradient(from 0deg, #ff0000, #ff8800, #ffff00, #00ff00, #0088ff, #8800ff, #ff0000)' },
  { id: 'bass-bloom', label: 'Bass Bloom', description: 'Expanding rings triggered by bass hits', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'radial-gradient(circle, #ff4400 0%, #ff8800 40%, #220000 100%)' },
  { id: 'spectrum-waterfall', label: 'Spectrum Waterfall', description: 'Audio spectrum scrolling down like a waterfall', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'linear-gradient(180deg, #00ffff 0%, #0088ff 30%, #004488 60%, #000022 100%)' },
  { id: 'strobe-color', label: 'Color Strobe', description: 'BPM-synced strobe with color cycle', mode: 'procedural', preset: 'neon', previewPatternId: 'neon', preview: 'linear-gradient(90deg, #ff0000, #00ff00, #0000ff, #ff0000)' },
  { id: 'neon-sign', label: 'Neon Sign', description: 'Flickering neon tube effect with color glow', mode: 'procedural', preset: 'pulse-ring', previewPatternId: 'pulse-ring', preview: 'linear-gradient(90deg, #ff44ff 0%, #cc00cc 30%, #ff88ff 50%, #cc00cc 70%, #ff44ff 100%)' },
  { id: 'oil-slick', label: 'Oil Slick', description: 'Iridescent swirling rainbow surface', mode: 'procedural', preset: 'lava', previewPatternId: 'lava', preview: 'conic-gradient(from 45deg, #ff0088, #00ffcc, #ff8800, #8800ff, #00ff44, #ff0088)' },
  { id: 'starfield', label: 'Starfield', description: 'Warp-speed star tunnel through hyperspace', mode: 'procedural', preset: 'meteor', previewPatternId: 'meteor', preview: 'radial-gradient(circle, #ffffff 0%, #8888ff 20%, #0000aa 60%, #000000 100%)' },
  { id: 'lava-flow', label: 'Lava Flow', description: 'Molten lava slowly oozing with heat shimmer', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'linear-gradient(180deg, #ff2200 0%, #ff6600 30%, #cc3300 60%, #440000 100%)' },
  { id: 'aurora-curtain', label: 'Aurora Curtain', description: 'Flowing curtains of northern lights', mode: 'procedural', preset: 'aurora', previewPatternId: 'aurora', preview: 'linear-gradient(180deg, #00ffaa 0%, #0088ff 50%, #8800cc 100%)' },
  { id: 'digital-rain-v2', label: 'Digital Rain II', description: 'Matrix-style falling code columns with glow', mode: 'procedural', preset: 'matrix', previewPatternId: 'matrix', preview: 'linear-gradient(180deg, #00ff44 0%, #004422 50%, #000000 100%)' },
  { id: 'tie-dye', label: 'Tie Dye', description: 'Psychedelic concentric circle dye patterns', mode: 'procedural', preset: 'rainbow', previewPatternId: 'rainbow', preview: 'conic-gradient(from 0deg, #ff0000, #ffff00, #00ff00, #00ffff, #0000ff, #ff00ff, #ff0000)' },
  { id: 'plasma-ball', label: 'Plasma Ball', description: 'Electric tendrils emanating from center', mode: 'procedural', preset: 'lightning', previewPatternId: 'lightning', preview: 'radial-gradient(circle, #ffffff 0%, #8888ff 15%, #4400ff 40%, #110044 100%)' },
  { id: 'breathing-grid', label: 'Breathing Grid', description: 'Pulsing grid of glowing nodes synchronized to BPM', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'radial-gradient(circle at 25% 25%, #4488ff 0%, #000022 40%), radial-gradient(circle at 75% 75%, #4488ff 0%, #000022 40%)' },
  { id: 'kaleidoscope-v2', label: 'Kaleidoscope II', description: 'Multi-fold symmetry with fractal detail', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'conic-gradient(from 0deg, #ff0088, #8800ff, #0088ff, #00ff88, #88ff00, #ff8800, #ff0088)' },
  { id: 'particle-burst', label: 'Particle Burst', description: 'Explosive particle bursts at random positions', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'radial-gradient(circle, #ffff88 0%, #ff8800 30%, #ff0000 60%, #000000 100%)' },
  { id: 'voronoi', label: 'Voronoi', description: 'Cellular Voronoi diagram with glowing borders', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'conic-gradient(from 30deg at 30% 70%, #ff0055, #0055ff, #00ff88, #ff0055)' },
  { id: 'interference', label: 'Interference', description: 'Concentric wave interference patterns creating moire', mode: 'procedural', preset: 'ripple', previewPatternId: 'ripple', preview: 'radial-gradient(circle, #00ffff 0%, #0033aa 40%, #000066 70%, #000000 100%)' },
  { id: 'mirror-warp', label: 'Mirror Warp', description: 'Fluid motion mirrored on multiple axes', mode: 'procedural', preset: 'warp', previewPatternId: 'warp', preview: 'conic-gradient(from 45deg, #ff4488, #4488ff, #44ff88, #ff8844, #ff4488)' },
  { id: 'sand-dune', label: 'Sand Dune', description: 'Wind-rippled desert dunes with warm shifting sands', mode: 'procedural', preset: 'ripple', previewPatternId: 'ripple', preview: 'linear-gradient(135deg, #ff8800 0%, #ffcc44 30%, #cc6600 60%, #884400 100%)' },
  { id: 'retro-scan', label: 'Retro Scan', description: 'CRT scanline scan effect with phosphor glow', mode: 'procedural', preset: 'scanner', previewPatternId: 'scanner', preview: 'repeating-linear-gradient(180deg, #00ff44 0px, #00aa22 2px, #001100 4px)' },
  { id: 'deep-sea', label: 'Deep Sea', description: 'Bioluminescent creatures floating in the abyss', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(circle at 40% 60%, #0055aa 0%, #001133 50%, #000022 100%)' },
  { id: 'paint-drip', label: 'Paint Drip', description: 'Vibrant paint drips flowing down from the top', mode: 'procedural', preset: 'lava', previewPatternId: 'lava', preview: 'linear-gradient(180deg, #ff0055 0%, #ff8800 20%, #ffff00 40%, #00ff44 60%, #0044ff 80%, #8800ff 100%)' },
  { id: 'snow-globe', label: 'Snow Globe', description: 'Gently falling snowflakes with a warm glow center', mode: 'procedural', preset: 'sparkle', previewPatternId: 'sparkle', preview: 'radial-gradient(circle, #ffcc88 0%, #4488bb 40%, #001133 100%)' },
  { id: 'thermal-cam', label: 'Thermal Camera', description: 'Infrared heat map with hot/cold color mapping', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'linear-gradient(90deg, #0000ff 0%, #00ffff 25%, #00ff00 50%, #ffff00 75%, #ff0000 100%)' },
  { id: 'lissajous-v2', label: 'Lissajous II', description: 'Animated parametric Lissajous curves with color trails', mode: 'procedural', preset: 'ripple', previewPatternId: 'ripple', preview: 'radial-gradient(circle, #ff00ff 0%, #00ffff 40%, #000044 100%)' },
  { id: 'watercolor-wash', label: 'Watercolor Wash', description: 'Soft watercolor paint bleeding through wet paper', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(ellipse at 30% 40%, #ff9988 0%, #cc88ff 40%, #88ccff 80%)' },
  { id: 'pixel-sort', label: 'Pixel Sort', description: 'Glitchy pixel sorting with bright streaks', mode: 'procedural', preset: 'blocks', previewPatternId: 'blocks', preview: 'linear-gradient(90deg, #000000 0%, #ffffff 20%, #ff0088 40%, #000000 60%, #00ffff 80%, #000000 100%)' },
  { id: 'prism-split', label: 'Prism Split', description: 'White light refracting through a prism into rainbow', mode: 'procedural', preset: 'stained', previewPatternId: 'stained', preview: 'linear-gradient(135deg, #ffffff 0%, #ff0000 16%, #ff8800 33%, #ffff00 50%, #00ff00 67%, #0088ff 83%, #8800ff 100%)' },
  { id: 'fiber-optic', label: 'Fiber Optic', description: 'Glowing fiber optic strands with light tips', mode: 'procedural', preset: 'meteor', previewPatternId: 'meteor', preview: 'radial-gradient(circle at 50% 100%, #ffffff 0%, #aaaaff 5%, #0033aa 40%, #000022 100%)' },
  { id: 'mirror-tunnel', label: 'Mirror Tunnel', description: 'Infinite mirror hall zoom with color cycling', mode: 'procedural', preset: 'warp', previewPatternId: 'warp', preview: 'radial-gradient(circle, #ffffff 0%, #8844ff 20%, #0033aa 50%, #000011 100%)' },
  { id: 'bubble-wrap', label: 'Bubble Wrap', description: 'Satisfying iridescent bubbles floating up', mode: 'procedural', preset: 'ocean', previewPatternId: 'ocean', preview: 'radial-gradient(circle at 30% 30%, #ffffff 0%, #aaddff 20%, #0088cc 60%, #001133 100%)' },
  { id: 'lightning-storm', label: 'Lightning Storm', description: 'Dramatic lightning bolts flashing across a dark sky', mode: 'procedural', preset: 'lightning', previewPatternId: 'lightning', preview: 'radial-gradient(circle, #ffffff 0%, #aaaaff 10%, #0022aa 50%, #000022 100%)' },
  { id: 'neon-grid', label: 'Neon Grid', description: 'Tron-style glowing grid with moving scan lines', mode: 'procedural', preset: 'scanner', previewPatternId: 'scanner', preview: 'linear-gradient(0deg, transparent 48%, #00ffff 50%, transparent 52%), linear-gradient(90deg, transparent 48%, #00ffff 50%, transparent 52%)' },
  { id: 'oil-painting', label: 'Oil Painting', description: 'Thick impasto brushstrokes with rich texture', mode: 'procedural', preset: 'lava', previewPatternId: 'lava', preview: 'conic-gradient(from 20deg, #cc3322, #ee8833, #ddcc22, #22aa44, #2244cc, #aa22cc, #cc3322)' },
  { id: 'sunrise-horizon', label: 'Sunrise Horizon', description: 'Dramatic sunrise with god rays and warm sky gradient', mode: 'procedural', preset: 'fire', previewPatternId: 'fire', preview: 'linear-gradient(180deg, #220022 0%, #aa2200 30%, #ff6600 60%, #ffcc00 80%, #ffff88 100%)' },
]);

export const CARD_PATTERN_BANK = Object.freeze([
  ...CORE_CARD_PATTERN_BANK,
  ...EXTENDED_CARD_PATTERN_BANK,
]);

export const CARD_PATTERN_BY_ID = new Map(CARD_PATTERN_BANK.map(pattern => [pattern.id, pattern]));

const CARD_PATTERN_FINGERPRINTS = Object.freeze({
  aurora: {
    motionLabel: 'Curtain drift',
    tempoLabel: 'Slow',
    intensityLabel: 'Soft',
    cssClass: 'motion-drift',
    palette: ['#102b10', '#31ce73', '#56f2cd', '#7d44b7'],
    tags: ['calm', 'curtain', 'gradient'],
  },
  plasma: {
    motionLabel: 'Liquid fold',
    tempoLabel: 'Medium',
    intensityLabel: 'Colorful',
    cssClass: 'motion-liquid',
    palette: ['#5b1ac9', '#258bd8', '#18d6a3', '#b8fff0'],
    tags: ['liquid', 'fold', 'full-color'],
  },
  fire: {
    motionLabel: 'Rising flame',
    tempoLabel: 'Fast',
    intensityLabel: 'Hot',
    cssClass: 'motion-flame',
    palette: ['#220300', '#b81905', '#ff5c05', '#ffd45a'],
    tags: ['flame', 'warm', 'bright'],
  },
  ocean: {
    motionLabel: 'Rolling wave',
    tempoLabel: 'Medium',
    intensityLabel: 'Cool',
    cssClass: 'motion-wave',
    palette: ['#eefcff', '#49c7df', '#0975a7', '#101a64'],
    tags: ['wave', 'water', 'cool'],
  },
  ripple: {
    motionLabel: 'Expanding rings',
    tempoLabel: 'Medium',
    intensityLabel: 'Cool',
    cssClass: 'motion-ring',
    palette: ['#f2ffff', '#1acff2', '#1555b8', '#05093a'],
    tags: ['ring', 'pulse', 'water'],
  },
  lava: {
    motionLabel: 'Organic blobs',
    tempoLabel: 'Slow',
    intensityLabel: 'Warm',
    cssClass: 'motion-organic',
    palette: ['#290604', '#b51606', '#ff7a1a', '#ffd05a'],
    tags: ['blob', 'warm', 'organic'],
  },
  rainbow: {
    motionLabel: 'Spectrum travel',
    tempoLabel: 'Medium',
    intensityLabel: 'Full color',
    cssClass: 'motion-flow',
    palette: ['#ff334d', '#ffdd38', '#25d66f', '#2eb9ff', '#b842ff'],
    tags: ['spectrum', 'flow', 'saturated'],
  },
  sparkle: {
    motionLabel: 'Random sparks',
    tempoLabel: 'Fast',
    intensityLabel: 'Bright points',
    cssClass: 'motion-spark',
    palette: ['#09091e', '#fffbdd', '#b9dcff', '#ffd0b3'],
    tags: ['spark', 'random', 'points'],
  },
  twinkle: {
    motionLabel: 'Soft stars',
    tempoLabel: 'Slow',
    intensityLabel: 'Soft points',
    cssClass: 'motion-spark',
    palette: ['#080817', '#d2eeff', '#ffe5c7', '#c8ffeb'],
    tags: ['twinkle', 'soft', 'points'],
  },
  meteor: {
    motionLabel: 'Comet tail',
    tempoLabel: 'Fast',
    intensityLabel: 'Cool bright',
    cssClass: 'motion-comet',
    palette: ['#05051f', '#20246d', '#818cff', '#ffffff'],
    tags: ['comet', 'tail', 'directional'],
  },
  chase: {
    motionLabel: 'Chasing point',
    tempoLabel: 'Fast',
    intensityLabel: 'Focused',
    cssClass: 'motion-chase',
    palette: ['#050817', '#1c718f', '#55d4f7', '#ffffff'],
    tags: ['chase', 'dot', 'directional'],
  },
  scanner: {
    motionLabel: 'Sweep beam',
    tempoLabel: 'Medium',
    intensityLabel: 'Focused',
    cssClass: 'motion-scan',
    palette: ['#080808', '#641106', '#ff2d0d', '#ffffff'],
    tags: ['scan', 'beam', 'back-forth'],
  },
  breathe: {
    motionLabel: 'Breathing glow',
    tempoLabel: 'Slow',
    intensityLabel: 'Soft',
    cssClass: 'motion-breathe',
    palette: ['#05130d', '#096044', '#23ca94', '#d7fff0'],
    tags: ['breathe', 'calm', 'ambient'],
  },
  candle: {
    motionLabel: 'Small flicker',
    tempoLabel: 'Medium',
    intensityLabel: 'Warm soft',
    cssClass: 'motion-flame',
    palette: ['#190503', '#a64208', '#ff9a20', '#fff0b8'],
    tags: ['flicker', 'warm', 'quiet'],
  },
  ember: {
    motionLabel: 'Uneven ember',
    tempoLabel: 'Slow',
    intensityLabel: 'Warm low',
    cssClass: 'motion-organic',
    palette: ['#1c0501', '#6f1809', '#c54216', '#f18b38'],
    tags: ['ember', 'warm', 'low'],
  },
  lightning: {
    motionLabel: 'Electric strike',
    tempoLabel: 'Burst',
    intensityLabel: 'High contrast',
    cssClass: 'motion-strike',
    palette: ['#050516', '#4d55cf', '#b7bfff', '#ffffff'],
    tags: ['strike', 'electric', 'flash'],
  },
  neon: {
    motionLabel: 'Tube flicker',
    tempoLabel: 'Medium',
    intensityLabel: 'Saturated',
    cssClass: 'motion-flicker',
    palette: ['#f91aa6', '#13efcb', '#fff13a', '#101014'],
    tags: ['neon', 'flicker', 'segments'],
  },
  matrix: {
    motionLabel: 'Falling code',
    tempoLabel: 'Fast',
    intensityLabel: 'Green',
    cssClass: 'motion-rain',
    palette: ['#020902', '#075c16', '#16ff65', '#eaffef'],
    tags: ['rain', 'vertical', 'digital'],
  },
  heartbeat: {
    motionLabel: 'Double pulse',
    tempoLabel: 'Pulse',
    intensityLabel: 'Red',
    cssClass: 'motion-pulse',
    palette: ['#130004', '#7c0716', '#ff2440', '#ffbcc4'],
    tags: ['pulse', 'beat', 'red'],
  },
  stained: {
    motionLabel: 'Pane shift',
    tempoLabel: 'Slow',
    intensityLabel: 'Full color',
    cssClass: 'motion-pane',
    palette: ['#f43a16', '#f3b31c', '#26c466', '#1f75e8', '#b43be8'],
    tags: ['pane', 'color', 'structured'],
  },
  confetti: {
    motionLabel: 'Color pops',
    tempoLabel: 'Fast',
    intensityLabel: 'Bright points',
    cssClass: 'motion-spark',
    palette: ['#0b0b0d', '#ff2b75', '#22d987', '#ffd23f'],
    tags: ['confetti', 'random', 'points'],
  },
  warp: {
    motionLabel: 'Radial streaks',
    tempoLabel: 'Fast',
    intensityLabel: 'Bright',
    cssClass: 'motion-warp',
    palette: ['#02020c', '#171c68', '#788dff', '#ffffff'],
    tags: ['streak', 'radial', 'speed'],
  },
  'pulse-ring': {
    motionLabel: 'Center pulse',
    tempoLabel: 'Pulse',
    intensityLabel: 'Bright',
    cssClass: 'motion-ring',
    palette: ['#09020f', '#391060', '#e43dff', '#ffffff'],
    tags: ['ring', 'pulse', 'center'],
  },
  blocks: {
    motionLabel: 'Stepped blocks',
    tempoLabel: 'Medium',
    intensityLabel: 'Bold',
    cssClass: 'motion-block',
    palette: ['#ff2b73', '#ffd23f', '#24cc71', '#1ea5ff', '#7457ff'],
    tags: ['blocks', 'stepped', 'saturated'],
  },
  bloom: {
    motionLabel: 'Soft bloom',
    tempoLabel: 'Slow',
    intensityLabel: 'Soft warm',
    cssClass: 'motion-breathe',
    palette: ['#160711', '#7c244e', '#ff6fb5', '#ffe0aa'],
    tags: ['bloom', 'soft', 'floral'],
  },
  calm: {
    motionLabel: 'Low breath',
    tempoLabel: 'Slow',
    intensityLabel: 'Low',
    cssClass: 'motion-breathe',
    palette: ['#06161d', '#14525c', '#22907e', '#aef5e5'],
    tags: ['calm', 'low', 'ambient'],
  },
  drift: {
    motionLabel: 'Pastel drift',
    tempoLabel: 'Slow',
    intensityLabel: 'Soft color',
    cssClass: 'motion-drift',
    palette: ['#7fc7ff', '#d9a8ff', '#ffc2d6', '#ffe7a8'],
    tags: ['pastel', 'drift', 'soft'],
  },
  wave: {
    motionLabel: 'Sine wave',
    tempoLabel: 'Medium',
    intensityLabel: 'Cool',
    cssClass: 'motion-wave',
    palette: ['#121445', '#5c5cc8', '#a9a9ee', '#d7d8ff'],
    tags: ['wave', 'sine', 'cool'],
  },
  sunset: {
    motionLabel: 'Warm drift',
    tempoLabel: 'Slow',
    intensityLabel: 'Warm color',
    cssClass: 'motion-drift',
    palette: ['#2a0830', '#8a2050', '#d04a18', '#f1c40f'],
    tags: ['sunset', 'warm', 'drift'],
  },
  'warm-white': {
    motionLabel: 'Steady output',
    tempoLabel: 'Static',
    intensityLabel: 'Warm white',
    cssClass: 'motion-static',
    palette: ['#2f2113', '#b98644', '#f4e4c7', '#fff6dd'],
    tags: ['white', 'steady', 'installation'],
  },
});

export function getCardPatternById(id) {
  return CARD_PATTERN_BY_ID.get(String(id || '').trim().toLowerCase()) || null;
}

export function getCardPatternRuntimeId(patternOrId) {
  const pattern = typeof patternOrId === 'object' && patternOrId
    ? patternOrId
    : getCardPatternById(patternOrId);
  return String(
    pattern?.preset ||
    pattern?.runtimePatternId ||
    pattern?.id ||
    patternOrId ||
    '',
  ).trim().toLowerCase();
}

export function orderedCardPatterns(ids = []) {
  const requested = [...new Set((Array.isArray(ids) ? ids : [])
    .map(id => String(id || '').trim().toLowerCase())
    .filter(Boolean))];
  const selected = requested.map(getCardPatternById).filter(Boolean);
  return selected.length ? selected : CARD_PATTERN_BANK;
}

export function getCardPatternFingerprint(patternOrId) {
  const pattern = typeof patternOrId === 'object' && patternOrId
    ? patternOrId
    : getCardPatternById(patternOrId);
  const id = String(pattern?.id || patternOrId || '').trim().toLowerCase();
  const runtimeId = getCardPatternRuntimeId(pattern || id);
  const metadata = CARD_PATTERN_FINGERPRINTS[id] ||
    (runtimeId && runtimeId !== id ? CARD_PATTERN_FINGERPRINTS[runtimeId] : null) ||
    makeFallbackFingerprint(pattern, id);
  return {
    id,
    motionLabel: metadata.motionLabel,
    tempoLabel: metadata.tempoLabel,
    intensityLabel: metadata.intensityLabel,
    cssClass: metadata.cssClass,
    palette: [...metadata.palette],
    tags: [...metadata.tags],
  };
}

function makeFallbackFingerprint(pattern = {}, id = '') {
  const label = pattern?.label || titleFromId(id) || 'Pattern';
  return {
    motionLabel: label,
    tempoLabel: 'Medium',
    intensityLabel: pattern?.mode === 'preset' ? 'Static' : 'Pattern',
    cssClass: 'motion-flow',
    palette: ['#1c2230', '#4e9ec9', '#8ce2d3'],
    tags: ['pattern', pattern?.mode || 'procedural'],
  };
}

function titleFromId(value = '') {
  return String(value || '')
    .split('-')
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}
