[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
lib_deps =
  fastled/FastLED
  bblanchon/ArduinoJson
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DLW_SD_CS=10
  -DLW_SPI_MOSI=11
  -DLW_SPI_SCK=12
  -DLW_SPI_MISO=13
  -DLW_MAX_PIXELS=1024
